#The MIT License (MIT)
#
#Copyright (c) 2015 University of Central Florida's Computer Software Engineering
#Scalable & Secure Systems (CSE - S3) Lab
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
#


tervelBufferWF:
	$(MAKE) test input="tervel_api/wf_ringbuffer_api.h" output="buffer_tervel_wf.x" cSources=$(tervelSources) cINC=$(tervelINC) cFlags=$(tervelFlags)

tervelBufferMcasLF:
	$(MAKE) test input="tervel_api/lf_mcasbuffer_api.h" output="buffer_tervel_mcas_lf.x" cSources=$(tervelSources) cINC=$(tervelINC) cFlags=$(tervelFlags)

# tsigasBuffer:
#	$(MAKE) test input="api/ringbuffer/tsigas.h" output="buffer_tsigas_nb.x" cINC="-I/Libraries/cds-1.2.0/ " cLIB="-L/Libraries/cds-1.2.0/bin/gcc-amd64-linux-64 -lrt  -lcds"

tbbBuffer:
	$(MAKE) test input="api/ringbuffer/tbb.h" output="buffer_tbb_fg.x" cLIB="-ltbb"

lockBuffer:
	$(MAKE) test input="api/ringbuffer/lock.h" output="buffer_lock_cg.x"

linuxBuffer:
	$(MAKE) test input="api/ringbuffer/linux.h" output="buffer_linux_nb.x"

naiveBuffer:
	$(MAKE) test input="api/ringbuffer/naive.h" output="buffer_naive_cg.x"
